[theme]

# Primary accent for interactive elements
primaryColor = '#D8EADE'

# Background color for the main content area
backgroundColor = '#101112'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#068506'

# Color used for almost all text
textColor = '#E6DAE5'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"
